name: Build

on:
  push:
  pull_request:
  schedule:
    # runs the CI everyday at 10AM
    - cron: "0 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel:
          - dev
          # - stable

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Add pub cache bin to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Add pub cache to PATH
        run: echo "PUB_CACHE="$HOME/.pub-cache"" >> $GITHUB_ENV

      - name: Install dependencies
        run: dart pub get && cd flutter_packages && flutter pub get && cd -

      - name: Check format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze

      - name: Run tests
        run: dart test

      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash | bash
